apiVersion: v1
kind: PersistentVolume
metadata:
  name: nm-postgres-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/postgresql/nm-postgresql-pv
  # storageClassName: standard
  storageClassName: worker02-nfs-storageclass

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nm-postgresql-pvc
  namespace: nm-postgresql
spec:
  resources:
    requests:
      storage: 2Gi 
  accessModes:
    - ReadWriteOnce
  volumeName: nm-postgres-pv
  storageClassName: worker02-nfs-storageclass

---

apiVersion: v1
kind: Service
metadata:
  name: nm-postgresql-service
  namespace: nm-postgresql
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: nm-postgresql
  type: NodePort

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nm-postgresql
  namespace: nm-postgresql
spec:
  serviceName: "nm-postgresql-service"
  replicas: 1
  selector:
    matchLabels:
      app: nm-postgresql
  template:
    metadata:
      labels:
        app: nm-postgresql
    spec:
      securityContext:
        fsGroup: 999
      containers:
        - name: nm-postgresql
          image: postgres:13
          ports:
            - containerPort: 5432
              name: nm-postgres
              protocol: TCP
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          command: [ 'postgres', '-c', 'wal_level=logical' ]
          securityContext:
            runAsUser: 999
            runAsGroup: 999
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: nm-postgresql-pvc
  # volumeClaimTemplates:                 
  # - metadata:
  #     name: postgres-storage
  #   spec:
  #     accessModes: [ "ReadWriteOnce" ]
  #     resources:
  #       requests:
  #         storage: 2Gi
      # storageClassName: worker02-nfs-storageclass