apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: nm-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
      - name: kafka-ui
        image: provectuslabs/kafka-ui:latest
        ports:
        - containerPort: 8080
        env:
        - name: DYNAMIC_CONFIG_ENABLED
          value: "true"
        - name: KAFKA_CLUSTERS_0_NAME
          value: "local"
        - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
          value: "broker-incluster:29092"
        - name: KAFKA_CLUSTERS_0_ZOOKEEPER
          value: "zookeeper:2181"
        - name: KAFKA_CLUSTERS_0_METRICS_PORT
          value: "9101"
        - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME
          value: "connect-debezium"
        - name: KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS
          value: "http://connect-debezium:8083"
        # - name: KAFKA_CLUSTERS_0_SCHEMAREGISTRY
        #   value: "http://schema-registry:8081"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: nm-kafka
spec:
  selector:
    app: kafka-ui
  ports:
    - name: kafka-ui
      port: 8080
      targetPort: 8080
      nodePort: 30800
  type: NodePort
