apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-flink
  namespace: nm-flink
spec:
  ingressClassName: nginx
  rules:
  - host: flink.pnm.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flink-session-cluster-rest
            port:
              number: 8081
