apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flink-session-cluster
spec:
  image: minhdata/kafka-flink-nessie-iceberg-python:1.16.1
  flinkVersion: v1_16
  mode: standalone # native
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "4"
  serviceAccount: flink 
  jobManager:
    resource:
      memory: "1024m"  
      cpu: 1       
  taskManager:
    resource:
      memory: "1024m"  
      cpu: 1         
    replicas: 2        